### ISSUE TITLE
Uninstall Katoolin

### ISSUE THREAD

**Issue by fratellomio** [LionSec/wifresti#8]
Hi after I installed Katoolin in my Ubuntu 15.10, I can't open my Ubuntu Software Center and Software & Updates menu.
when I open the Ubuntu Software Center, it comes with these following error:

 ERROR:root:DebFileApplication import
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/**init**.py", line 4, in <module>
    from debfile import DebFileApplication, DebFileOpenError
  File "/usr/share/software-center/softwarecenter/db/debfile.py", line 25, in <module>
    from softwarecenter.db.application import Application, AppDetails
  File "/usr/share/software-center/softwarecenter/db/application.py", line 28, in <module>
    import softwarecenter.distro
  File "/usr/share/software-center/softwarecenter/distro/**init**.py", line 199, in <module>
    distro_instance = _get_distro()
  File "/usr/share/software-center/softwarecenter/distro/__init__.py", line 174, in _get_distro
    module = __import__(distro_module_name, globals(), locals(), [], -1)
ImportError: No module named kali
Traceback (most recent call last):
  File "/usr/bin/software-center", line 128, in <module>
    from softwarecenter.ui.gtk3.app import SoftwareCenterAppGtk3
  File "/usr/share/software-center/softwarecenter/ui/gtk3/app.py", line 54, in <module>
    from softwarecenter.db.application import Application
  File "/usr/share/software-center/softwarecenter/db/application.py", line 28, in <module>
    import softwarecenter.distro
  File "/usr/share/software-center/softwarecenter/distro/**init**.py", line 199, in <module>
    distro_instance = _get_distro()
  File "/usr/share/software-center/softwarecenter/distro/__init__.py", line 174, in _get_distro
    module = __import__(distro_module_name, globals(), locals(), [], -1)
ImportError: No module named kali

and when I open my the Software & Updates, it comes with these following issue:
![screenshot from 2015-11-21 11-10-16](https://cloud.githubusercontent.com/assets/6015405/11355307/b3d114b6-9286-11e5-96ad-e5ae3708a28b.png)

**Comment by gigili** [comment]
Not sure if it will truly delete everything but you can use this answer:  http://askubuntu.com/a/708848/444056

But before you remove the katoolin file there is a line in there on the line 138 that has the install script for all the packages which you can copy & paste it just replace the apt-get install with apt-get remove and it will remove everything. But before you run the remove script, at the end of that line there is command to download and extract an archive remove that and then run it.  And then use apt-get autoremove to clear all the libraries that were installed with the tools.

These are not official nor confirmed remove options and all commands need to be run with root permission 

Also if you find that there are still kali tools listed in your menu after you removed them, use this commands:
sudo apt-get remove --purge kali-menu && apt-get clean
sudo apt-get remove --purge classicmenu-indicator && apt-get clean

I just used all of these commands to remove it from my system. I'm using linux mint 17.3

**Comment by fr3lin** [comment]
I am using Ubuntu 15.10 and had the same problem.
The solution below has fixed my problem:

`gksu gedit /etc/*release`

Change the file like this (this is for 15.10 but you can change accordingly)

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=Wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
```

save and close the file.

`gksu gedit /etc/*issue`

Change the file like this (this is for 15.10 but you can change accordingly)

`Ubuntu 15.10 \n \l`

save and close the file.

`sudo apt-get install --reinstall software-center`

I hope it also works for you.

**Comment by smartechdigitalz** [comment]
> 

Hi... The command gksu gedit /etc/*release isn't running...

It's feedback error
